Vlad us 272
stasiukk/tryCloud pull request #3
Opened 2024-10-29 20:07 UTC by vladimircasap

Positive TC Done

2024-10-29 20:14 UTC, stasiukk approved these changes
I ran your code,  and it looks great! Good job!

2024-10-30 15:22 UTC, Haden-Z requested changes
Hi Vladimir,
Your codes are ok, but
I suggest to use Scenario Outline.
I want to see the data that you use on the Feature file.

2024-10-30 17:00 UTC, vladimircasap commented
> Hi Vladimir, Your codes are ok, but I suggest to use Scenario Outline. I want to see the data that you use on the Feature file.

Added negative scenario,
Added Scenario Outline

2024-10-31 17:27 UTC, Haden-Z approved these changes

2024-10-31 17:31 UTC, merged